#!/bin/bash
SCRIPT_HOME=/sources/ALFS/
# 2.3

LFS_HDD=/dev/sda
LFS_PARTITION_SWAP=/dev/sda5
LFS_PARTITION_ROOT=/dev/sda3

#2.4 
LFS_MOUNT=/mnt/lfs

#3.all
#DOIT later

#4.3
LFS_USER=lfs
LFS_GROUP=lfs
LFS_PASSWORD=1
LFS_SCRIPT_HOME=/home/lfs/setup-scripts
LFS_BUILD_LOGS=$LFS_MOUNT/build-logs
LFS_BUILD_LOGS_MAIN_5=$LFS_BUILD_LOGS/chapter_5_0.log
LFS_BUILD_LOGS_5=$LFS_BUILD_LOGS/ch$CH/
LFS_MOUNT_TOOLS=$LFS_MOUNT/tools
LFS_MOUNT_SOURCES=$LFS_MOUNT/sources

# 5.4 and more
PROCESSOR_CORES=-j2

# 6.2 and more
LFS_BUILD_LOGS_6_HOST=$LFS_BUILD_LOGS/ch$CH
LFS_BUILD_LOGS_TARGET=/build-logs
LFS_BUILD_LOGS_6=$LFS_BUILD_LOGS_TARGET/ch$CH/

# 6.9
LFS_TIME_ZONE=AFRICA/CAIRO
if [ $CH = 6 ];then
	LOG_FILE=$LFS_BUILD_LOGS_6$CH_SEC
elif [ $CH =5 ];then
	LOG_FILE=$LFS_BUILD_LOGS_5$CH_SEC
fi

